### PR TITLE
Cm 12.1

### PR DESCRIPTION
**Pull request by andrwgldmn**
revert  deleting strings concerning WCNSS_qcom_wlan_nv.bin cause I add that as **zombah** in his repo

### CODE REVIEW

**Comment by zombah** [comment]
I don't understand what do you mean with this pr can you please describe more details.

**Comment by andrwgldmn** [comment]
i added this file to dir "wifi"and added some strings about this file to ara.mk like in your repo

**Comment by zombah** [comment]
Is this firmware with regulatory fix like here https://github.com/cm-nokia-x2/proprietary_vendor_nokia_ara/commit/4d78661e362b2d07d5c5eed57b855e3bbfaf2ebf ??
And please make cleaner PR without this create xyz, delete xyz

**Comment by andrwgldmn** [comment]
yes. ok, those deleting&creating were randomness..

**Pull request closed without merging**
